### ISSUE TITLE
Tabular Input and Normalization

### ISSUE THREAD

**Issue by j-e-dalton** [nutterb/HydeNet#33]
In the original pass at the package, while we were still in the conceptualization phase, you made some functions which facilitated tabular input of factors.

I think that either you made other functions or such functions already existed which normalized conditional probability tables so that they represented proper conditional probability distributions (specifically, integrate to 1, all probabilities in [0,1] for each combination of unobserved parent nodes).  Or maybe you (or others) didn't do this.  Can't remember.

**Comment by nutterb** [comment]
I think I had done this in some form, but we abandoned it under the new format.  Could you describe how you would like to use the functionality?

**Comment by j-e-dalton** [comment]
Yes, I think this was originally in the pgm library.  Doesn't mean we need to use it though, of course.

At the fundamental level, there will commonly be situations where discrete probability distributions (e.g. 2x2 tables) would most easily be specified in some sort of tabular format.  If we have training data, then modelToNode.xtabs() handles this nicely.  If we are pulling frequencies or proportions from the literature (e.g., sensitivity/specificity of a diagnostic test), then inputting the probability distributions is currently cumbersome given the fact that we only have 2 numbers that completely capture the conditional probability distributions for the node.

**Comment by nutterb** [comment]
`modelToNode.xtabs` only handles this well when there is a single variable in the call.  If we were to have something like `xtabs(~ disease + test)` to generate the 2x2 table associated with diagnostic performance, it would fail.  This seems like a pretty glaring hole.  

I'll need some advice on how to address this, though.  In `xtabs(~ disease + test)`, neither `disease` nor `test` has a parent, nor is a child of the other.  So the correct way to decompose this would be to marginalize over each dimension and reduce it to `xtabs(~disease)` and `xtabs(~test)`, correct?  If so, this could be generalized to any number of variables.  The effect would be that passing `xtabs(~ disease + test)` to `HydeNetwork.list` should create two separate nodes not connected to each other?

**Comment by jarrod-dalton** [comment]
I think that by rule modelToNode.xtabs should "normalize" tables in such a way that probabilities sum to 1 for every combination of parent nodes.  Wherever there are combinations with 0 cell counts for each value of the child node, we might give a warning message and assign the discrete uniform distribution across all levels of the child variable.

A more elegant approach might be to set an optional parameter minCellCount=0.  The function would then look at each of the observed combinations of parent node values and flag the combinations for which the total (marginal across the values of the child node)  number of observations is <minCellCount. The qualifying combinations (and all unobserved combinations not present in the xtabs object would then be given the same "all others" conditional probability distribution. This is worth considering if we can do it because it would allow for large reductions in table storage and probably quicker computation.  How we make this work with JAGS I have no clue.

Independent of the above, the issue with modelToNode being able to discern the network structure from all other methods but not xtabs leads me to propose the requirement of 1) the xtabs object (obviously) and 2) a dag()-like formula that makes explicit the subnetwork structure involving the nodes in the xtabs object,

**Comment by jarrod-dalton** [comment]
Moving this to Issue #38.
