### ISSUE TITLE
Bug in vectorProbs()

### ISSUE THREAD

**Issue by j-e-dalton** [nutterb/HydeNet#4]
When you use setNode() in conjunction with vectorProbs, you can inherit the node parameter:

net <- setNode(net, wells,
               nodeType = "dcat",
               pi = vectorProbs(p = c(.3, .6, .1)) )

But when you do this, it doesn't construct the nodeParams string correctly:

net$nodeParams$wells
## [1] "pi.[1] <- 0.3; pi.[2] <- 0.6; pi.[3] <- 0.1"

It should be:

**Comment by nutterb** [comment]
This is a quirk I'm not sure how to program my way out of.  `vectorProbs` was meant to be a convenience that would allow the user to not have to remember the correct specification of the JAGS code.  The downside is that, being an independent function, there's no good way to manipulate the scoping to get it to pull the node name from the network (because it isn't applied to a network, it is applied to a function).

How would you feel if I, instead, put in a parameter check that cast an error if `node` is missing.  At least then the user will be reminded that they need to indicate which node these are applied to.

``` r
vectorProbs <- function(p, node, normalize=TRUE){
  if (missing(node)) stop("Please provide the node name (note: spelling is important)")
  node <- as.character(substitute(node))
  if (normalize) p <- p/sum(p)
  paste0("pi.", node, "[", 1:length(p), "] <- ", p, collapse="; ")
}
```
