### ISSUE TITLE
summary() methods for `HydeNetwork` objects

### ISSUE THREAD

**Issue by jarrod-dalton** [nutterb/HydeNet#43]
For (uncompiled) `HydeNetwork` objects, some sort of printout listing nodes within each node type:

```
Decision Nodes:
  hit1 | initialPoints*dealerUpcard       some_useful_stuff
  hit2 | pointsAfterCard3*dealerUpcard    some_useful_stuff

Utility Nodes
  payoff | playerFinalPoints*dealerFinalPoints      some_more_useful_stuff

Random Variable Nodes:
  card1           dcat    some_other_useful_stuff
  card2           dcat    some_other_useful_stuff
  card3 | hit1    dcat    some_other_useful_stuff
  card4 | hit2    dcat    some_other_useful_stuff
  card5 | hit3    dcat    some_other_useful_stuff

Deterministic Nodes
  etc
  etc
  etc
```

For `compiled.HydeNetwork` objects, perhaps this could be annotated with some node type(/node istribution)-specific summary statistics.  Or perhaps not...

**Comment by jarrod-dalton** [comment]
This is not a version 1.0 issue.

**Comment by nutterb** [comment]
So, assuming that this should be a cleaner look than the `print` method, let's say we want to keep it limited to one line per node.  The big question is, what is useful stuff?  

I wouldn't want to use the node formula, because that's generally the biggest and messiest piece of the specification.  I think the other most interesting pieces of information are 
1. the `nodeFitter`
2. If it has a model attached
3. And if it is in a data set (either `nodeData` or `data`

Is there anything else worth including?  Are any of those three really not that interesting? (if none of them are that interesting, I'm not opposed to what you'e described above without the useful stuff column.  It's still easier to browse than the print output)

For `compiled.HydeNetwork` objects, I'm not sure what the summary would look like.  Maybe just a repeat of the `HydeNetwork` summary but with an additional piece indicating the observed variables?  and for a `compiledDecisionModel`, it would show the policy matrix.  But there aren't any real numeric summaries to be had until the posterior distributions have been run.

**Comment by nutterb** [comment]
So when I tried to include the parents of each node, in some cases the summary string started to wrap and it started to look pretty messy.  So I've switched it up to just give the number of parents. It looks good, but I'm not sure about it's utility.  Here's a look:

(I've included it in my last commit, but it won't pass checks)

``` r
> summary(BlackJack)
Decision Nodes: 
  hit1  |  2 parents  |  (no policies defined)
  hit2  |  2 parents  |  (no policies defined)
  hit3  |  2 parents  |  (no policies defined)

Utility Nodes: 
  payoff  |  2 parents

Deterministic Nodes: 
  initialAces        |  2 parents
  initialPoints      |  2 parents
  highUpcard         |   1 parent
  acesAfterCard3     |  2 parents
  pointsAfterCard3   |  4 parents
  acesAfterCard4     |  2 parents
  pointsAfterCard4   |  5 parents
  acesAfterCard5     |  2 parents
  pointsAfterCard5   |  6 parents
  playerFinalPoints  |  7 parents

Random Nodes: 
  card1              |  0 parents  |  dcat 
  card2              |  0 parents  |  dcat 
  dealerUpcard       |  0 parents  |  dcat 
  card3              |  0 parents  |  dcat 
  card4              |  0 parents  |  dcat 
  card5              |  0 parents  |  dcat 
  dealerFinalPoints  |   1 parent  |  dnorm
```

**Comment by jarrod-dalton** [comment]
I think this looks good. And I can't come up with anything better
(er...what about this: limit print width to 80 characters, and for nodes
with 3 or fewer parents, list them explicitly. truncate down to 80
characters with "..." if needed. For nodes with 4 or more parents, just
say, e.g., "7 parents".)

**Comment by nutterb** [comment]
Made some changes.  The node name column takes up to twenty characters before truncating with `...`, and then the remaining width in `options("width")` is split between two columns, each of which will truncate with `...` when exceeded.  That way the summary output will almost always fit within the user's width option.
