### ISSUE TITLE
setNodeModels() for multiple nodes using a single GLM

### ISSUE THREAD

**Issue by jarrod-dalton** [nutterb/HydeNet#45]
See the Decision Networks vignette, under section 'Decision Nodes'.  What if we wished to use a single GLM to populate the node distributions for `hit1`, `hit2` and `hit3`?

I don't think we can do that without renaming stuff and/or re-estimating the model?

**Comment by nutterb** [comment]
So you mean to define `glm.hit1` and then give that same model to all three nodes?  I think I see where you're going with that, because all three are based on the points up to that moment in the game and the `highUpcard`.  But to make this work, at the very least, we'd have to map the names from the model to the network structure.  We could probably provide a utility to do that, but I think we'd end up refitting the models underneath the hood somewhere anyway.  And I worry that this would be one of those things where we might have our "intended" purpose, but when released to a wider user base, it may not get used as intended, prove to be buggy and cause errors, and result in people abandoning the package.

**Comment by jarrod-dalton** [comment]
I'll add that, after thinking about this some more, the copy of models idea should be avoidable once we go to Markov dynamic Bayesian networks.
