### ISSUE TITLE
HydeNet Model Gallery

### ISSUE THREAD

**Issue by jarrod-dalton** [nutterb/HydeNet#51]
We should start thinking about how we advertise and interact with the user community.
What should we put on the GitHub package homepage?

One idea I had was to put, right at the top of the page, an invitation for people to contribute working HydeNet analyses to a HydeNet model gallery that we host.  What is the minimal set of things needed to do something like this?  

Since I'm trying to learn GitHub, maybe you can walk me through this.  What I'm thinking is a subdirectory called modelGallery with its own subdirectories called 'vignettes' and 'data'.  We would need to put stuff in the .gitIgnore and .RBuildIgnore files to ignore this stuff.  Then, we would manually edit a table on the package homepage with the various analyses people contribute.

However, I'm confused by the fact that this approach wouldn't allow users to download the package and play with contributers' .Rdata objects.  That would mean the .RData objects would have to be built with the package, right?

What if the modelGallery subdirectory was actually an R package itself?  Still ignored, but downloadable and installable, either as a zip file or from source.

**Comment by nutterb** [comment]
We could put in another branch, `-modelGallery` that could be an entirely separate package.  (for this example, let's call it `HydeNetGallery`. We can load the data sets and examples there and people can install it with 

`devtools::install_github("nutterb/HydeNet", ref="modelGallery")`

If we don't try to upload it to CRAN, we can get away with a little more flexibility to some of the quirks that make it into the package.  But I'll probably try to keep it pretty clean, because I'm obsessive like that.

I think it's a good idea, and I can start laying out the structure of that branch while I wait for your phone call.

**Comment by nutterb** [comment]
http://nutterb.github.io/HydeNet/

Go the the link above.  I've included the Decision Nodes vignette as an example on the web page.

To add additional examples, all you need to do is 
- open up the gh-pages branch
- place an Rmd in the vignettes directory
- run the Rmd to create the html file
- in the main directory, knit run `index.Rhtml`
- commit changes

We can spend more time tweaking the look and feel of the page, but it opens up the possibility of a gallery, which is probably a better place for things like my conditional nodes example, rather than putting more and more vignettes into the package.
