### ISSUE TITLE
Validation warning message in setNode

### ISSUE THREAD

**Issue by jarrod-dalton** [nutterb/HydeNet#61]
## Validation has been ignored for parameters defined with character strings

This seems to be showing up with every call to `setNode` in the `DecisionNetworks` vignette. Is there a way to suppress this message?

**Comment by jarrod-dalton** [comment]
Here's a screenshot:

![image](https://cloud.githubusercontent.com/assets/11472793/7771978/2b213a2e-0069-11e5-856b-89aec0694d19.png)

**Comment by nutterb** [comment]
Some of this is by design.  `vectorProbs` is returning JAGS code, which we can't validate directly.  IN this instance, I can't really do much but set `validate = FALSE`.  I went ahead and did that in most of the vignette calls.  I also added a note above the first call giving a brief description of what would happen.  The note advises the user to look at the documentation of `setNode` for more details.

The one thing I did fix is we were generating the same message about validation whenever we used `fromFormula` and `fromData`.  That shouldn't happen because, presumably, `HydeNet` will build the JAGS code correctly.  That cut down on a lot of these messages.
